# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: microservices/Catalog/Catalog.API/Dockerfile
    ports:
      - 5028:5028
